# $Id$

# -----------------------------------------------------------------------
# The macro for the Virtual Geometry Model test
# Copyright (C) 2007, Ivana Hrivnacova               
# All rights reserved. 
#           
# For the licensing terms see vgm/LICENSE.
# Contact: ivana@ipno.in2p3.fr
# -----------------------------------------------------------------------

/tracking/verbose 1
/run/beamOn 1000

