# $Id$

# -----------------------------------------------------------------------
# The macro for the Virtual Geometry Model test
# Copyright (C) 2007, Ivana Hrivnacova               
# All rights reserved. 
#           
# For the licensing terms see vgm/LICENSE.
# Contact: ivana@ipno.in2p3.fr
# -----------------------------------------------------------------------

#
# Sets some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# create empty scene
#
/vis/scene/create
#
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#
#/vis/open DAWNFILE
/vis/open OGL
#/vis/open OIX
#/vis/open RayTracer
/vis/viewer/set/projection perspective

#
#/vis/scene/add/axes
/vis/viewer/set/viewpointThetaPhi 30 45
/vis/viewer/flush
#
# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
#
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
